name: Build IzPack Installer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -X

      - name: List target directory
        run: ls -la target

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: target/the-example-installer.jar
          if-no-files-found: error
