name: Build IzPack Installer

on:
  push:
    branches:
      - izpack5-1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create target directory
        run: mkdir -p target

      - name: Build with Maven
        run: |
          mvn -f ../pom.xml clean package -X > build.log 2>&1
          cat build.log

      - name: List directory structure
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing target directory:"
          ls -la ../target || echo "Target directory does not exist."
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: installer/target/jcg-23-installer.jar
          if-no-files-found: error 
